var texts = [
  "┃",
  "┣ Biomes",
  "┃ ┣ Cork Forest",
  "┃ ┗ Teste",
  "┃",
  "┣ Structures",
  "┃ ┗ Wine Trader House",
  "┃",
  "┣ Automation",
  "┃ ┣ Ore Extractor",
  "┃ ┣ Gas Extractor",
  "┃ ┣ Fluid Extractor",
  "┃ ┗ Distillation Tower",
  "┃",
  "┣ Energy",
  "┃ ┣ Renewable Energy",
  "┃ ┃ ┣ Biomass",
  "┃ ┃ ┣ Geothermal",
  "┃ ┃ ┣ Hydropower",
  "┃ ┃ ┣ Solar",
  "┃ ┃ ┗ Wind",
  "┃ ┗ Non-Renewable Energy",
  "┃ ㅤ  ┣ Coal",
  "┃ ㅤ  ┣ Gas",
  "┃ ㅤ  ┣ Nuclear",
  "┃ ㅤ  ┗ Oil",
  "┃",
  "┣ Farming",
  "┃ ┣ Animals",
  "┃ ┣ Crops",
  "┃ ┣ Trees",
  "┃ ┣ Fishing",
  "┃ ┗ Winery",
  "┃",
  "┣ Cooking",
  "┃ ┗ None",
  "┃",
  "┣ Entities",
  "┃ ┗ None",
  "┃",
  "┣ Resources",
  "┃ ┣ Deposits",
  "┃ ┗ Oil",
  "┃",
  "┣ Smelting",
  "┃ ┗ None",
  "┃",
  "┣ Magic",
  "┃ ┗ None",
  "┃",
  "┗ Wizardry",
  "ㅤ┣ Knowledge Book",
  "ㅤ┣ Spawner Upgrades",
  "ㅤ┗ Pentagram",
];
var nav = document.getElementById("nav");

texts.forEach(function (text) {
  nav.innerHTML += "<p>" + text + "</p>";
});
