var texts = [
  "All Content:",
  "ㅤ",
  "┏ Automation:",
  "┃ ┃",
  "┃ ┣ Ore Extractor",
  "┃ ┣ Ore Detection",
  "┃ ┣ Gas Extractor",
  "┃ ┗ Fluid Extractor (WIP)",
  "┃",
  "┣ Energy:",
  "┃",
  "┣ Exploration:",
  "┃ ┃",
  "┃ ┣ Biomes:",
  "┃ ┃┗ Cork Forest",
  "┃ ┃",
  "┃ ┣ Entities:",
  "┃ ┃",
  "┃ ┗ Structures:",
  "┃ㅤ ┗ Wine Trader House",
  "┃",
  "┣ Food:",
  "┃ ┃",
  "┃ ┗ Winery:",
  "┃ㅤ ┣ Growing Grapes",
  "┃ㅤ ┣ Treader & Presser",
  "┃ㅤ ┣ Fermenting",
  "┃ㅤ ┗ Selling Wines",
  "┃",
  "┣ Magic:",
  "┃",
  "┣ Smelting:",
  "┃",
  "┗ Wizardry:",
  "ㅤ ┃",
  "ㅤ ┣ Knowledge Book:",
  "ㅤ ┃   ┣ Knowledge Sacrifice",
  "ㅤ ┃   ┣ Knowledge Bookshelf",
  "ㅤ ┃   ┗ Knowledge Book",
  "ㅤ ┃",
  "ㅤ ┣ Souls:",
  "ㅤ ┃   ┣ Getting Souls",
  "ㅤ ┃   ┗ Selling Souls",
  "ㅤ ┃",
  "ㅤ ┣ Spawner Upgrades:",
  "ㅤ ┃   ┣ Getting a Spawner",
  "ㅤ ┃   ┣ Spawner Shards",
  "ㅤ ┃   ┗ Spawner Core",
  "ㅤ ┃   ㅤ ┗ Spawner Upgrades",
  "ㅤ ┃",
  "ㅤ ┣Effects:",
  "ㅤ ┃ ┣Cursed",
  "ㅤ ┃ ┣Water Curse",
  "ㅤ ┃ ┣Fire Curse",
  "ㅤ ┃ ┣Nature Curse",
  "ㅤ ┃ ┣Earth Curse",
  "ㅤ ┃ ┣Air Curse",
  "ㅤ ┃ ┣Light Curse",
  "ㅤ ┃ ┣Darkness Curse",
  "ㅤ ┃ ┣Void Curse",
  "ㅤ ┃ ┣Mana Curse",
  "ㅤ ┃ ┣Sound Curse",
  "ㅤ ┃ ┗Time Curse",
  "ㅤ ┃",
  "ㅤ ┗ Pentagram:",
  "ㅤ ㅤ ┗ WIP",
];
var nav = document.getElementById("nav");

texts.forEach(function (text) {
  nav.innerHTML += "<p>" + text + "</p>";
});